version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      # Mount the source code for live-reloading during development
      - .:/app
      # Mount the SQLite database file to persist user data
      - ./users.db:/app/users.db
      # Mount the projects directory used by ingest_api
      - ~/private-ai/projects:/root/private-ai/projects
    env_file:
      - .env
    depends_on:
      - qdrant
      - ollama

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "11435:11435"
    volumes:
      - ./ollama_data:/root/.ollama